### ISSUE TITLE
选择完menuItem后，再进行选择，点击上一次选择的此次不起作用

### ISSUE THREAD

**Issue by wade555** [tinper-bee/bee-dropdown#4]
选择完menuItem后，再进行选择，点击上一次选择的此次点击不起作用，看它的 aria-selected 为 true，没有进行重置。

**Comment by BoyuZhou** [comment]
@wade555  是要取消选中吗

**Comment by BoyuZhou** [comment]
@wade555 你试一下给Menu组件，添加一个onClick事件，这个是可以每次都触发的，你看一下是不是满足你的需求呢

**Comment by wade555** [comment]
click事件可以了，感谢！！！
